CREATE DATABASE Desarrollo_De_Sistemas_I
use desarrollo_de_sistemas_i

create table PERSONA (
IdPersona INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Apellidos VARCHAR(150) NOT NULL,
Telefono VARCHAR(15) NULL, --POR SI PONE +591
CI VARCHAR (15) NULL,
Correo VARCHAR (100) NULL,
Estado VARCHAR(100) NOT NULL
)

CREATE TABLE USUARIO (
IdUsuario INT NOT NULL PRIMARY KEY,
IdPersona INT NOT NULL,
NombreUser VARCHAR (100) NOT NULL,
Contraseña VARCHAR (15) NOT NULL,
FechaReg DATE NOT NULL,
FOREIGN KEY	(IdPersona) REFERENCES PERSONA (IdPersona)
)

CREATE TABLE ROL (
 IdRol INT NOT NULL PRIMARY KEY,
 Nombre VARCHAR(100) NOT NULL,
 Estado VARCHAR(100) NOT NULL
)

CREATE TABLE USUARIOROL (
IdUsuarioRol INT NOT NULL PRIMARY KEY,
IdUsuario INT NOT NULL,
IdRol INT NOT NULL,
FechaAsignada DATE NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IdUsuario) REFERENCES USUARIO (IDUSUARIO),
FOREIGN KEY (IdRol) REFERENCES ROL (IDROL)
)

CREATE TABLE CLIENTE (
IdCliente INT NOT NULL PRIMARY KEY,
IdPersona INT NOT NULL,
TipoCliente VARCHAR(100) NOT NULL,
CodigoCliente INT NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA)
)

CREATE TABLE VENTA(
IdVenta INT NOT NULL PRIMARY KEY,
Idcliente INT NOT NULL,
IdVendedor INT,
Fecha DATE,
Total INT NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
FOREIGN KEY (IDVENDEDOR) REFERENCES USUARIO (IDUSUARIO)
)

CREATE TABLE TIPOPROD (
IdTipoProd INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Estado VARCHAR(100) NOT NULL
)

CREATE TABLE MARCA(
IdMarca INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Estado VARCHAR(100) NOT NULL
)

CREATE TABLE PRODUCTO (
IdProducto INT NOT NULL PRIMARY KEY,
IdTipoProducto INT NOT NULL,
Nombre VARCHAR(100) NOT NULL,
CodigoBarra INT NOT NULL,
IdMarca INT NOT NULL,
Unidad INT NOT NULL,
Descripcion VARCHAR (300) NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDTIPOPRODUCTO) REFERENCES TIPOPROD (IDTIPOPROD),
FOREIGN KEY (IDMARCA) REFERENCES MARCA (IDMARCA)
)

CREATE TABLE PROVEEDOR (
IdProveedor INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(100) NOT NULL,
Telefono VARCHAR(15) NOT NULL,
Direccion VARCHAR(300) NOT NULL,
Estado VARCHAR(100) NOT NULL
)

CREATE TABLE PROVEE (
IdProvee INT NOT NULL PRIMARY KEY,
IdProducto INT NOT NULL,
IdProveedor INT NOT NULL,
Fecha DATE  NOT NULL,
Precio INT NOT NULL,
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR)
)

CREATE TABLE DETALLEVENT (
IdDetalleVent INT NOT NULL PRIMARY KEY,
IdVenta INT NOT NULL,
IdProducto INT NOT NULL,
Cantidad INT NOT NULL,
PrecioVenta INT NOT NULL,
SubTotal INT NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO)
)

CREATE TABLE INGRESO (
IdIngreso INT NOT NULL PRIMARY KEY,
IdProveedor INT NOT NULL,
FechaIngreso DATE NOT NULL,
Total INT NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR)
)

CREATE TABLE DETALLEING (
IdDetalleIng INT NOT NULL PRIMARY KEY,
IdProducto INT NOT NULL,
IdIngreso INT NOT NULL,
FechaVenc INT NULL,
Cantidad INT NOT NULL,
PrecioCosto INT NOT NULL,
PrecioVenta INT NOT NULL,
Subtotal INT NOT NULL,
Estado VARCHAR(100) NOT NULL,
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
FOREIGN KEY (IDINGRESO) REFERENCES INGRESO (IDINGRESO)
)
drop table venta
drop table detallevent